radiusDBConfigs:
 username : root
 password : root
 DBName : radius
 host : localhost
 port : 3306

summaryDBConfigs:
 username : root
 password : root123
 DBName : summary
 host : localhost
 port : 3306

dashboardDBConfigs:
 username : root
 password : root
 DBName : dashboard
 host : localhost
 port : 3306

portalDBConfigs:
 username : root
 password : root
 DBName : portal
 host : localhost
 port : 3306

serverConfigs:
 httpPort : 8081
 httpsPort : 9443
 adminPort : 9463
 readTimeOut : 20
 writeTimeOut : 20

redisConfigs:
 serverUrl : localhost
 serverPort : 6379
 password : root
 db : 0

accountingConfigs:
 validityPeriod : 3600

# log configurations
logsDirectory : logs
httpAccessLogs : true
httpAccessLogFileName : http-access.log
serverLogFileName : server.log
